# Sample .travis.yml for R projects from https://github.com/craigcitro/r-travis

language: node_js
node_js:
  - "node"
  - "6"
  - "6.1"
  - "5.11"
  - "4"
  - "4.2.4"
env:
  - global:
    - WARNINGS_ARE_ERRORS=1

notifications:
  email:
    on_success: change
    on_failure: change
